#include "GunAnimationData.h"
#include <vector>

namespace Hiwoong::GunAnimationData
{
	const SpriteAnimationClip Fire =
	{
		{
			// 0: 작은 불꽃
			SpriteFrame(
            {
                "                         ",
                "            *            ",
                "           ***           ",
                "            _            ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] ",
                "[#####|:|#######|:|#####]"
            },
            {
                "                         ",
                "            W            ",
                "           WWW           ",
                "            W            ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW ",
                "WWWWWWWWWWWWWWWWWWWWWWWWW"
            }
        ),

		// 1: 불꽃이 크게 퍼짐
		SpriteFrame(
            {
                "        *   |   *        ",
                "         **###**         ",
                "       --##@##@##--      ",
                "         **#_#**         ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] ",
                "[#####|:|#######|:|#####]"
            },
            {
                "        W   W   W        ",
                "         WWWWWWW         ",
                "       WWWWWWWWWWWW      ",
                "         WWWWWWW         ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW ",
                "WWWWWWWWWWWWWWWWWWWWWWWWW"
            }
        ),

		// 2: 불꽃이 줄어들며 총이 한 줄 올라감
		SpriteFrame(
            {
                "         *  |  *         ",
                "          **#**          ",
                "           *_*           ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] ",
                "[#####|:|#######|:|#####]",
                "[#####|:|#######|:|#####]"
            },
            {
                "         W  W  W         ",
                "          WWWWW          ",
                "           WWW           ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW ",
                "WWWWWWWWWWWWWWWWWWWWWWWWW",
                "WWWWWWWWWWWWWWWWWWWWWWWWW"
            }
        ),

		// 3: 최대 반동 총이 두 줄 올라감
		SpriteFrame(
            {
                "          .   .          ",
                "            _            ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] ",
                "[#####|:|#######|:|#####]",
                "[#####|:|#######|:|#####]",
                "[#####|:|#######|:|#####]"
            },
            {
                "          W   W          ",
                "            W            ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW ",
                "WWWWWWWWWWWWWWWWWWWWWWWWW",
                "WWWWWWWWWWWWWWWWWWWWWWWWW",
                "WWWWWWWWWWWWWWWWWWWWWWWWW"
            }
        ),

		// 4: 반동에서 복귀 한 줄 올라온 위치
		SpriteFrame(
            {
                "                         ",
                "                         ",
                "            _            ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] ",
                "[#####|:|#######|:|#####]",
                "[#####|:|#######|:|#####]"
            },
            {
                "                         ",
                "                         ",
                "            W            ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW ",
                "WWWWWWWWWWWWWWWWWWWWWWWWW",
                "WWWWWWWWWWWWWWWWWWWWWWWWW"
            }
        ),

		// 5: 평상시 모습으로 복귀
		SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "            _            ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] ",
                "[#####|:|#######|:|#####]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "            W            ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW ",
                "WWWWWWWWWWWWWWWWWWWWWWWWW"
            }
        )
    }, 0.4, false, true
	};

    const SpriteAnimationClip Reload =
    {
        {
            Fire.frames.back(),
            SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            _            ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            W            ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            _            ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            W            ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            _            ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            W            ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           _             ",
                "          |#|            ",
                "        __|#|__          ",
                "       [=======]         ",
                "       |-------|         ",
                "        |:::::::|        ",
                "        |-------|#]      ",
                "       [|=======|#]      ",
                "      [#|_______|##]     ",
                "      [#[=======]###]    ",
                "      [#|#######|###]    ",
                "     [##|:|=====|:|###]  ",
                "    [###|:|#####|:|###]  ",
                "    [###|:|=====|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           W             ",
                "          WWW            ",
                "        WWWWWWW          ",
                "       WWWWWWWWW         ",
                "       WWWWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWWWW      ",
                "       WWWWWWWWWWWW      ",
                "      WWWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "      WWWWWWWWWWWWWWW    ",
                "     WWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           _             ",
                "          |#|            ",
                "        __|#|__          ",
                "       [=======]         ",
                "       |-------|         ",
                "        |:::::::|        ",
                "        |-------|#]      ",
                "       [|=======|#]      ",
                "      [#|_______|##]     ",
                "      [#[=======]###]    ",
                "      [#|#######|###]    ",
                "     [##|:|=====|:|###]  ",
                "    [###|:|#####|:|###]  ",
                "    [###|:|=====|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           W             ",
                "          WWW            ",
                "        WWWWWWW          ",
                "       WWWWWWWWW         ",
                "       WWWWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWWWW      ",
                "       WWWWWWWWWWWW      ",
                "      WWWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "      WWWWWWWWWWWWWWW    ",
                "     WWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           _             ",
                "          |#|            ",
                "        __|#|__          ",
                "       [=======]         ",
                "       |-------|         ",
                "        |:::::::|        ",
                "        |-------|#]      ",
                "       [|=======|#]      ",
                "      [#|_______|##]     ",
                "      [#[=======]###]    ",
                "      [#|#######|###]    ",
                "     [##|:|=====|:|###]  ",
                "    [###|:|#####|:|###]  ",
                "    [###|:|=====|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           W             ",
                "          WWW            ",
                "        WWWWWWW          ",
                "       WWWWWWWWW         ",
                "       WWWWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWWWW      ",
                "       WWWWWWWWWWWW      ",
                "      WWWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "      WWWWWWWWWWWWWWW    ",
                "     WWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          _              ",
                "         |#|             ",
                "       __|#|__           ",
                "      [=======]          ",
                "      |-------|          ",
                "       |:::::::|#]       ",
                "        |-------|##]     ",
                "       [|=======|##]     ",
                "      [#|_______|###]    ",
                "        [=====][####]    ",
                "        |:::::|[####]    ",
                "        |-----||####|    ",
                "        |:::::||####|    ",
                "        [=====][#####]   "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          W              ",
                "         WWW             ",
                "       WWWWWWW           ",
                "      WWWWWWWWW          ",
                "      WWWWWWWWW          ",
                "       WWWWWWWWWWW       ",
                "        WWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWWW   "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          _              ",
                "         |#|             ",
                "       __|#|__           ",
                "      [=======]          ",
                "      |-------|          ",
                "       |:::::::|#]       ",
                "        |-------|##]     ",
                "       [|=======|##]     ",
                "      [#|_______|###]    ",
                "        [=====][####]    ",
                "        |:::::|[####]    ",
                "        |-----||####|    ",
                "        |:::::||####|    ",
                "        [=====][#####]   "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          W              ",
                "         WWW             ",
                "       WWWWWWW           ",
                "      WWWWWWWWW          ",
                "      WWWWWWWWW          ",
                "       WWWWWWWWWWW       ",
                "        WWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWWW   "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          _              ",
                "         |#|             ",
                "       __|#|__           ",
                "      [=======]          ",
                "      |-------|          ",
                "       |:::::::|#]       ",
                "        |-------|##]     ",
                "       [|=======|##]     ",
                "      [#|_______|###]    ",
                "        [=====][####]    ",
                "        |:::::|[####]    ",
                "        |-----||####|    ",
                "        |:::::||####|    ",
                "        [=====][#####]   "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          W              ",
                "         WWW             ",
                "       WWWWWWW           ",
                "      WWWWWWWWW          ",
                "      WWWWWWWWW          ",
                "       WWWWWWWWWWW       ",
                "        WWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWWW   "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         _               ",
                "        |#|              ",
                "      __|#|__            ",
                "     [=======]           ",
                "      |-------|#]        ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|##]     ",
                "       [#|_______|###]   ",
                "         [===]  [#####]  ",
                "         |:::|  |#####|  ",
                "         |---|  |#####|  ",
                "         |:::|  |#####|  ",
                "         |---| [#######] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         W               ",
                "        WWW              ",
                "      WWWWWWW            ",
                "     WWWWWWWWW           ",
                "      WWWWWWWWWWW        ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW WWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         _               ",
                "        |#|              ",
                "      __|#|__            ",
                "     [=======]           ",
                "      |-------|#]        ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|##]     ",
                "       [#|_______|###]   ",
                "         [===]  [#####]  ",
                "         |:::|  |#####|  ",
                "         |---|  |#####|  ",
                "         |:::|  |#####|  ",
                "         |---| [#######] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         W               ",
                "        WWW              ",
                "      WWWWWWW            ",
                "     WWWWWWWWW           ",
                "      WWWWWWWWWWW        ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW WWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         _               ",
                "        |#|              ",
                "      __|#|__            ",
                "     [=======]           ",
                "      |-------|#]        ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|##]     ",
                "       [#|_______|###]   ",
                "         [===]  [#####]  ",
                "         |:::|  |#####|  ",
                "         |---|  |#####|  ",
                "         |:::|  |#####|  ",
                "         |---| [#######] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         W               ",
                "        WWW              ",
                "      WWWWWWW            ",
                "     WWWWWWWWW           ",
                "      WWWWWWWWWWW        ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW WWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [===]   |#####| ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "         [===]   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "         [===]  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "                [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "                WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "                [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "                WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "                [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "                WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "                [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "                WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "                [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "                WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "                [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "                WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "                [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "                WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "                [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "                WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "                 |#####| ",
                "         [===]  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "                 WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "                 |#####| ",
                "         [===]   |#####| ",
                "         |:::|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "                 WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "         [===]   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "         [===]   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [___]   |#####| ",
                "         [===]   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [   ]   [#####] ",
                "         [===]   |#####| ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         W   W   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]",
                "         |:::|           "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW",
                "         WWWWW           "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        _                ",
                "       |#|               ",
                "     __|#|__             ",
                "    [=======]            ",
                "     |-------|#]         ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|###]    ",
                "       [#|_______|###]   ",
                "         [===]   [#####] ",
                "         |:::|   |#####| ",
                "         |---|   |#####| ",
                "         |:::|   |#####| ",
                "         |---|  [#######]"
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "        W                ",
                "       WWW               ",
                "     WWWWWWW             ",
                "    WWWWWWWWW            ",
                "     WWWWWWWWWWW         ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWWW    ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW   WWWWWWW ",
                "         WWWWW  WWWWWWWWW"
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         _               ",
                "        |#|              ",
                "      __|#|__            ",
                "     [=======]           ",
                "      |-------|#]        ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|##]     ",
                "       [#|_______|###]   ",
                "         [===]  [#####]  ",
                "         |:::|  |#####|  ",
                "         |---|  |#####|  ",
                "         |:::|  |#####|  ",
                "         |---| [#######] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         W               ",
                "        WWW              ",
                "      WWWWWWW            ",
                "     WWWWWWWWW           ",
                "      WWWWWWWWWWW        ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW WWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         _               ",
                "        |#|              ",
                "      __|#|__            ",
                "     [=======]           ",
                "      |-------|#]        ",
                "      |:::::::|##]       ",
                "       |-------|##]      ",
                "       [|=======|##]     ",
                "       [#|_______|###]   ",
                "         [===]  [#####]  ",
                "         |:::|  |#####|  ",
                "         |---|  |#####|  ",
                "         |:::|  |#####|  ",
                "         |---| [#######] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "         W               ",
                "        WWW              ",
                "      WWWWWWW            ",
                "     WWWWWWWWW           ",
                "      WWWWWWWWWWW        ",
                "      WWWWWWWWWWWW       ",
                "       WWWWWWWWWWWW      ",
                "       WWWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWWWW   ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW  WWWWWWW  ",
                "         WWWWW WWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          _              ",
                "         |#|             ",
                "       __|#|__           ",
                "      [=======]          ",
                "      |-------|          ",
                "       |:::::::|#]       ",
                "        |-------|##]     ",
                "       [|=======|##]     ",
                "      [#|_______|###]    ",
                "        [=====][####]    ",
                "        |:::::|[####]    ",
                "        |-----||####|    ",
                "        |:::::||####|    ",
                "        [=====][#####]   "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          W              ",
                "         WWW             ",
                "       WWWWWWW           ",
                "      WWWWWWWWW          ",
                "      WWWWWWWWW          ",
                "       WWWWWWWWWWW       ",
                "        WWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWWW   "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          _              ",
                "         |#|             ",
                "       __|#|__           ",
                "      [=======]          ",
                "      |-------|          ",
                "       |:::::::|#]       ",
                "        |-------|##]     ",
                "       [|=======|##]     ",
                "      [#|_______|###]    ",
                "        [=====][####]    ",
                "        |:::::|[####]    ",
                "        |-----||####|    ",
                "        |:::::||####|    ",
                "        [=====][#####]   "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "          W              ",
                "         WWW             ",
                "       WWWWWWW           ",
                "      WWWWWWWWW          ",
                "      WWWWWWWWW          ",
                "       WWWWWWWWWWW       ",
                "        WWWWWWWWWWWW     ",
                "       WWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWW    ",
                "        WWWWWWWWWWWWWW   "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           _             ",
                "          |#|            ",
                "        __|#|__          ",
                "       [=======]         ",
                "       |-------|         ",
                "        |:::::::|        ",
                "        |-------|#]      ",
                "       [|=======|#]      ",
                "      [#|_______|##]     ",
                "      [#[=======]###]    ",
                "      [#|#######|###]    ",
                "     [##|:|=====|:|###]  ",
                "    [###|:|#####|:|###]  ",
                "    [###|:|=====|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           W             ",
                "          WWW            ",
                "        WWWWWWW          ",
                "       WWWWWWWWW         ",
                "       WWWWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWWWW      ",
                "       WWWWWWWWWWWW      ",
                "      WWWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "      WWWWWWWWWWWWWWW    ",
                "     WWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           _             ",
                "          |#|            ",
                "        __|#|__          ",
                "       [=======]         ",
                "       |-------|         ",
                "        |:::::::|        ",
                "        |-------|#]      ",
                "       [|=======|#]      ",
                "      [#|_______|##]     ",
                "      [#[=======]###]    ",
                "      [#|#######|###]    ",
                "     [##|:|=====|:|###]  ",
                "    [###|:|#####|:|###]  ",
                "    [###|:|=====|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "           W             ",
                "          WWW            ",
                "        WWWWWWW          ",
                "       WWWWWWWWW         ",
                "       WWWWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWWWW      ",
                "       WWWWWWWWWWWW      ",
                "      WWWWWWWWWWWWWW     ",
                "      WWWWWWWWWWWWWWW    ",
                "      WWWWWWWWWWWWWWW    ",
                "     WWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWW  ",
                "    WWWWWWWWWWWWWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            _            ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            W            ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW "
            }
        ),
        SpriteFrame(
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            _            ",
                "           |#|           ",
                "         __|#|__         ",
                "        [=======]        ",
                "        |-------|        ",
                "        |:::::::|        ",
                "        |-------|        ",
                "       [|=======|]       ",
                "      [#|_______|#]      ",
                "     [##[=======]##]     ",
                "    [###|#######|###]    ",
                "   [##|:|=======|:|##]   ",
                "  [###|:|#######|:|###]  ",
                " [####|:|=======|:|####] "
            },
            {
                "                         ",
                "                         ",
                "                         ",
                "                         ",
                "            W            ",
                "           WWW           ",
                "         WWWWWWW         ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "        WWWWWWWWW        ",
                "       WWWWWWWWWWW       ",
                "      WWWWWWWWWWWWW      ",
                "     WWWWWWWWWWWWWWW     ",
                "    WWWWWWWWWWWWWWWWW    ",
                "   WWWWWWWWWWWWWWWWWWW   ",
                "  WWWWWWWWWWWWWWWWWWWWW  ",
                " WWWWWWWWWWWWWWWWWWWWWWW "
            }
        ),
        Fire.frames.back()
   },
   1.80,
   false,
   true
  };
}